name: Krusty Krab Recipes API CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Build with Maven
        run: ./mvnw clean install
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm generate-api-client